[package]
name = "rich-phantoms"
version = "0.1.0"
authors = ["David McGillicuddy <contact@djmcgill.co.uk>"]
edition = "2018"

[dev-dependencies]
compiletest_rs = { version = "0.3", features = ["stable"] }
